//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingStartedClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference2.ICsvService")]
    public interface ICsvService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICsvService/GetName", ReplyAction="http://Microsoft.ServiceModel.Samples/ICsvService/GetNameResponse")]
        string GetName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICsvService/GetName", ReplyAction="http://Microsoft.ServiceModel.Samples/ICsvService/GetNameResponse")]
        System.Threading.Tasks.Task<string> GetNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICsvService/UpdateName", ReplyAction="http://Microsoft.ServiceModel.Samples/ICsvService/UpdateNameResponse")]
        string UpdateName(string updatedName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICsvService/UpdateName", ReplyAction="http://Microsoft.ServiceModel.Samples/ICsvService/UpdateNameResponse")]
        System.Threading.Tasks.Task<string> UpdateNameAsync(string updatedName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICsvService/GetCity", ReplyAction="http://Microsoft.ServiceModel.Samples/ICsvService/GetCityResponse")]
        string GetCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICsvService/GetCity", ReplyAction="http://Microsoft.ServiceModel.Samples/ICsvService/GetCityResponse")]
        System.Threading.Tasks.Task<string> GetCityAsync(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICsvServiceChannel : GettingStartedClient.ServiceReference2.ICsvService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CsvServiceClient : System.ServiceModel.ClientBase<GettingStartedClient.ServiceReference2.ICsvService>, GettingStartedClient.ServiceReference2.ICsvService {
        
        public CsvServiceClient() {
        }
        
        public CsvServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CsvServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CsvServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CsvServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetName(string name) {
            return base.Channel.GetName(name);
        }
        
        public System.Threading.Tasks.Task<string> GetNameAsync(string name) {
            return base.Channel.GetNameAsync(name);
        }
        
        public string UpdateName(string updatedName) {
            return base.Channel.UpdateName(updatedName);
        }
        
        public System.Threading.Tasks.Task<string> UpdateNameAsync(string updatedName) {
            return base.Channel.UpdateNameAsync(updatedName);
        }
        
        public string GetCity(string city) {
            return base.Channel.GetCity(city);
        }
        
        public System.Threading.Tasks.Task<string> GetCityAsync(string city) {
            return base.Channel.GetCityAsync(city);
        }
    }
}
